#pragma once

#include <unordered_map>
#include <string>

#include "tokens.hpp"

enum NodeType {
    Null = 0,
    End,
    Semicolon,
    Number,
    Identifier,
    PrintAscii,
    PrintInt,
    ReadInt,
    While,
    If,
    Add,
    Sub,
    Mul,
    Div,
    Less,
    Equal,
    Greater,
    Identical,
    LessOrEqual,
    NotIdentical,
    GreaterOrEqual,
    Def,
    Call,
    Return,
};

inline const std::unordered_map<NodeType, std::string> kNodeTypeToString {
    {End, keyEnd},
    {Semicolon, keySemicolon},
    {Number, keyNumber},
    {Identifier, keyIdentifier},
    {PrintAscii, keyPrintAscii},
    {PrintInt, keyPrintInt},
    {ReadInt, keyReadInt},
    {While, keyWhile},
    {If, keyIf},
    {Add, keyAdd},
    {Sub, keySub},
    {Mul, keyMul},
    {Div, keyDiv},
    {Less, keyLess},
    {Equal, keyEqual},
    {Greater, keyGreater},
    {Identical, keyIdentical},
    {LessOrEqual, keyLessOrEqual},
    {NotIdentical, keyNotIdentical},
    {GreaterOrEqual, keyGreaterOrEqual},
    {Def, keyDef},  
    {Call, keyCall},
    {Return, keyReturn},
};

inline const std::unordered_map<std::string, NodeType> kStringToNodeType {
    {keyNumber, Number},
    {keyIdentifier, Identifier},
    {keyDef, Def},
    {keySemicolon, Semicolon},
    {keyPrintAscii, PrintAscii},
    {keyPrintInt, PrintInt},
    {keyReadInt, ReadInt},
    {keyWhile, While},
    {keyIf, If},
    {keyAdd, Add},
    {keySub, Sub},
    {keyMul, Mul},
    {keyDiv, Div},
    {keyLess, Less},
    {keyEqual, Equal},
    {keyGreater, Greater},
    {keyIdentical, Identical},
    {keyLessOrEqual, LessOrEqual},
    {keyNotIdentical, NotIdentical},
    {keyGreaterOrEqual, GreaterOrEqual},
    {keyCall, Call},
    {keyReturn, Return},
    {keyEnd, End},
};
